In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold, RepeatedKFold, GroupKFold

In [6]:
data = { 'Hours_Studied': [1,2,3,4,5,6,2,7,8,1], 
         'Attendance': [60,65,70,72,80,85,50,90,95,55], 
         'Passed': [0,0,1,1,1,1,0,1,1,0] # 1=Yes, 0=No 
       } 
df = pd.DataFrame(data) 
X = df[['Hours_Studied', 'Attendance']] 
y = df['Passed']

In [8]:
df.shape

(10, 3)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Hours_Studied  10 non-null     int64
 1   Attendance     10 non-null     int64
 2   Passed         10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [10]:
df

   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
2              3          70       1
3              4          72       1
4              5          80       1
5              6          85       1
6              2          50       0
7              7          90       1
8              8          95       1
9              1          55       0

In [30]:
df.iloc[[4,6]]

   Hours_Studied  Attendance  Passed
4              5          80       1
6              2          50       0

# KFold

In [42]:
kf = KFold(n_splits=3, shuffle=True, random_state=None)
for fold, (train_idx, val_idx) in enumerate(kf.split(df), start=1): 
    train_set = df.iloc[train_idx] 
    val_set = df.iloc[val_idx] 
    print(f"\nFold {fold}") 
    print("Validation Set:") 
    print(val_set) 
    print("Training Set:") 
    print(train_set)

Fold 1
Validation Set:
   Hours_Studied  Attendance  Passed
2              3          70       1
4              5          80       1
5              6          85       1
7              7          90       1
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
3              4          72       1
6              2          50       0
8              8          95       1
9              1          55       0

Fold 2
Validation Set:
   Hours_Studied  Attendance  Passed
1              2          65       0
3              4          72       1
8              8          95       1
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
2              3          70       1
4              5          80       1
5              6          85       1
6              2          50       0
7              7          90       1
9              1          55       0

Fold 3
Validation Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
6              2          50       0
9              1          55       0
Training Set:
   Hours_Studied  Attendance  Passed
1              2          65       0
2              3          70       1
3              4          72       1
4              5          80       1
5              6          85       1
7              7          90       1
8              8          95       1

In [47]:
rkf = RepeatedKFold(n_splits=3, n_repeats=3, random_state=42)
for fold, (train_idx, val_idx) in enumerate(rkf.split(df), start=1): 
    train_set = df.iloc[train_idx] 
    val_set = df.iloc[val_idx] 
    print(f"\nFold {fold}") 
    print("Validation Set:") 
    print(val_set) 
    print("Training Set:") 
    print(train_set)

Fold 1
Validation Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
5              6          85       1
8              8          95       1
Training Set:
   Hours_Studied  Attendance  Passed
2              3          70       1
3              4          72       1
4              5          80       1
6              2          50       0
7              7          90       1
9              1          55       0

Fold 2
Validation Set:
   Hours_Studied  Attendance  Passed
2              3          70       1
7              7          90       1
9              1          55       0
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
3              4          72       1
4              5          80       1
5              6          85       1
6              2          50       0
8              8          95       1

Fold 3
Validation Set:
   Hours_Studied  Attendance  Passed
3              4          72       1
4              5          80       1
6              2          50       0
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
2              3          70       1
5              6          85       1
7              7          90       1
8              8          95       1
9              1          55       0

Fold 4
Validation Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
5              6          85       1
8              8          95       1
Training Set:
   Hours_Studied  Attendance  Passed
2              3          70       1
3              4          72       1
4              5          80       1
6              2          50       0
7              7          90       1
9              1          55       0

Fold 5
Validation Set:
   Hours_Studied  Attendance  Passed
3              4          72       1
4              5          80       1
7              7          90       1
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
2              3          70       1
5              6          85       1
6              2          50       0
8              8          95       1
9              1          55       0

Fold 6
Validation Set:
   Hours_Studied  Attendance  Passed
2              3          70       1
6              2          50       0
9              1          55       0
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
3              4          72       1
4              5          80       1
5              6          85       1
7              7          90       1
8              8          95       1

Fold 7
Validation Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
2              3          70       1
6              2          50       0
9              1          55       0
Training Set:
   Hours_Studied  Attendance  Passed
1              2          65       0
3              4          72       1
4              5          80       1
5              6          85       1
7              7          90       1
8              8          95       1

Fold 8
Validation Set:
   Hours_Studied  Attendance  Passed
3              4          72       1
5              6          85       1
8              8          95       1
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
1              2          65       0
2              3          70       1
4              5          80       1
6              2          50       0
7              7          90       1
9              1          55       0

Fold 9
Validation Set:
   Hours_Studied  Attendance  Passed
1              2          65       0
4              5          80       1
7              7          90       1
Training Set:
   Hours_Studied  Attendance  Passed
0              1          60       0
2              3          70       1
3              4          72       1
5              6          85       1
6              2          50       0
8              8          95       1
9              1          55       0

In [62]:
Group = [1,1,2,2,3,3,4,4,5,5]
df["Group"] = Group
gkf = GroupKFold(n_splits=4) 
for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y, groups=df['Group']), 1): 
    print(f"\nFold {fold}") 
    print("Train groups:", df.iloc[train_idx]['Group'].unique()) 
    print("Validation groups:", df.iloc[val_idx]['Group'].unique())
    val_set = df.iloc[val_idx] 
    print(f"Validation set: {val_set}")

Fold 1
Train groups: [2 3 4]
Validation groups: [1 5]
Validation set:    Hours_Studied  Attendance  Passed  Group
0              1          60       0      1
1              2          65       0      1
8              8          95       1      5
9              1          55       0      5

Fold 2
Train groups: [1 2 3 5]
Validation groups: [4]
Validation set:    Hours_Studied  Attendance  Passed  Group
6              2          50       0      4
7              7          90       1      4

Fold 3
Train groups: [1 2 4 5]
Validation groups: [3]
Validation set:    Hours_Studied  Attendance  Passed  Group
4              5          80       1      3
5              6          85       1      3

Fold 4
Train groups: [1 3 4 5]
Validation groups: [2]
Validation set:    Hours_Studied  Attendance  Passed  Group
2              3          70       1      2
3              4          72       1      2

In [52]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
for train_index, test_index in loo.split(df):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [1 2 3 4 5 6 7 8 9] TEST: [0]
TRAIN: [0 2 3 4 5 6 7 8 9] TEST: [1]
TRAIN: [0 1 3 4 5 6 7 8 9] TEST: [2]
TRAIN: [0 1 2 4 5 6 7 8 9] TEST: [3]
TRAIN: [0 1 2 3 5 6 7 8 9] TEST: [4]
TRAIN: [0 1 2 3 4 6 7 8 9] TEST: [5]
TRAIN: [0 1 2 3 4 5 7 8 9] TEST: [6]
TRAIN: [0 1 2 3 4 5 6 8 9] TEST: [7]
TRAIN: [0 1 2 3 4 5 6 7 9] TEST: [8]
TRAIN: [0 1 2 3 4 5 6 7 8] TEST: [9]

In [54]:
y.value_counts()

Passed
1    6
0    4
Name: count, dtype: int64

In [58]:
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=3)
for train_index, test_index in skfold.split(X, y):
     print("TRAIN:", train_index, "TEST:", test_index)
     print(y[train_index].value_counts())
     print(y[test_index].value_counts())

TRAIN: [4 5 6 7 8 9] TEST: [0 1 2 3]
Passed
1    4
0    2
Name: count, dtype: int64
Passed
0    2
1    2
Name: count, dtype: int64
TRAIN: [0 1 2 3 7 8 9] TEST: [4 5 6]
Passed
1    4
0    3
Name: count, dtype: int64
Passed
1    2
0    1
Name: count, dtype: int64
TRAIN: [0 1 2 3 4 5 6] TEST: [7 8 9]
Passed
1    4
0    3
Name: count, dtype: int64
Passed
1    2
0    1
Name: count, dtype: int64